/*
Copyright 2022 The kubeall.com Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	metricsv1alpha1 "github.com/kubeall/api/metrics/v1alpha1"
	versioned "github.com/kubeall/client-go/metrics/clientset/versioned"
	internalinterfaces "github.com/kubeall/client-go/metrics/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/kubeall/client-go/metrics/listers/metrics/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ServiceMetricsInformer provides access to a shared informer and lister for
// ServiceMetricses.
type ServiceMetricsInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.ServiceMetricsLister
}

type serviceMetricsInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewServiceMetricsInformer constructs a new informer for ServiceMetrics type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewServiceMetricsInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredServiceMetricsInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredServiceMetricsInformer constructs a new informer for ServiceMetrics type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredServiceMetricsInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.MetricsV1alpha1().ServiceMetricses(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.MetricsV1alpha1().ServiceMetricses(namespace).Watch(context.TODO(), options)
			},
		},
		&metricsv1alpha1.ServiceMetrics{},
		resyncPeriod,
		indexers,
	)
}

func (f *serviceMetricsInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredServiceMetricsInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *serviceMetricsInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&metricsv1alpha1.ServiceMetrics{}, f.defaultInformer)
}

func (f *serviceMetricsInformer) Lister() v1alpha1.ServiceMetricsLister {
	return v1alpha1.NewServiceMetricsLister(f.Informer().GetIndexer())
}
