/*
Copyright 2022 The kubeall.com Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/kubeall/api/rbac/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeKubeUsers implements KubeUserInterface
type FakeKubeUsers struct {
	Fake *FakeRbacV1alpha1
}

var kubeusersResource = schema.GroupVersionResource{Group: "rbac.kubeall.com", Version: "v1alpha1", Resource: "kubeusers"}

var kubeusersKind = schema.GroupVersionKind{Group: "rbac.kubeall.com", Version: "v1alpha1", Kind: "KubeUser"}

// Get takes name of the kubeUser, and returns the corresponding kubeUser object, and an error if there is any.
func (c *FakeKubeUsers) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.KubeUser, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(kubeusersResource, name), &v1alpha1.KubeUser{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KubeUser), err
}

// List takes label and field selectors, and returns the list of KubeUsers that match those selectors.
func (c *FakeKubeUsers) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.KubeUserList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(kubeusersResource, kubeusersKind, opts), &v1alpha1.KubeUserList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.KubeUserList{ListMeta: obj.(*v1alpha1.KubeUserList).ListMeta}
	for _, item := range obj.(*v1alpha1.KubeUserList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested kubeUsers.
func (c *FakeKubeUsers) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(kubeusersResource, opts))
}

// Create takes the representation of a kubeUser and creates it.  Returns the server's representation of the kubeUser, and an error, if there is any.
func (c *FakeKubeUsers) Create(ctx context.Context, kubeUser *v1alpha1.KubeUser, opts v1.CreateOptions) (result *v1alpha1.KubeUser, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(kubeusersResource, kubeUser), &v1alpha1.KubeUser{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KubeUser), err
}

// Update takes the representation of a kubeUser and updates it. Returns the server's representation of the kubeUser, and an error, if there is any.
func (c *FakeKubeUsers) Update(ctx context.Context, kubeUser *v1alpha1.KubeUser, opts v1.UpdateOptions) (result *v1alpha1.KubeUser, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(kubeusersResource, kubeUser), &v1alpha1.KubeUser{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KubeUser), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeKubeUsers) UpdateStatus(ctx context.Context, kubeUser *v1alpha1.KubeUser, opts v1.UpdateOptions) (*v1alpha1.KubeUser, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(kubeusersResource, "status", kubeUser), &v1alpha1.KubeUser{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KubeUser), err
}

// Delete takes name of the kubeUser and deletes it. Returns an error if one occurs.
func (c *FakeKubeUsers) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(kubeusersResource, name, opts), &v1alpha1.KubeUser{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeKubeUsers) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(kubeusersResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.KubeUserList{})
	return err
}

// Patch applies the patch and returns the patched kubeUser.
func (c *FakeKubeUsers) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.KubeUser, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(kubeusersResource, name, pt, data, subresources...), &v1alpha1.KubeUser{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KubeUser), err
}
