/*
Copyright 2022 The kubeall.com Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	clusterv1alpha1 "github.com/kubeall/api/cluster/v1alpha1"
	versioned "github.com/kubeall/client-go/cluster/clientset/versioned"
	internalinterfaces "github.com/kubeall/client-go/cluster/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/kubeall/client-go/cluster/listers/cluster/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// UserKubeConfigInformer provides access to a shared informer and lister for
// UserKubeConfigs.
type UserKubeConfigInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.UserKubeConfigLister
}

type userKubeConfigInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewUserKubeConfigInformer constructs a new informer for UserKubeConfig type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewUserKubeConfigInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredUserKubeConfigInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredUserKubeConfigInformer constructs a new informer for UserKubeConfig type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredUserKubeConfigInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ClusterV1alpha1().UserKubeConfigs().List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ClusterV1alpha1().UserKubeConfigs().Watch(context.TODO(), options)
			},
		},
		&clusterv1alpha1.UserKubeConfig{},
		resyncPeriod,
		indexers,
	)
}

func (f *userKubeConfigInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredUserKubeConfigInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *userKubeConfigInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&clusterv1alpha1.UserKubeConfig{}, f.defaultInformer)
}

func (f *userKubeConfigInformer) Lister() v1alpha1.UserKubeConfigLister {
	return v1alpha1.NewUserKubeConfigLister(f.Informer().GetIndexer())
}
