/*
Copyright 2022 The kubeall.com Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/kubeall/api/rbac/v1alpha1"
	scheme "github.com/kubeall/client-go/rbac/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// UserKubeConfigsGetter has a method to return a UserKubeConfigInterface.
// A group's client should implement this interface.
type UserKubeConfigsGetter interface {
	UserKubeConfigs() UserKubeConfigInterface
}

// UserKubeConfigInterface has methods to work with UserKubeConfig resources.
type UserKubeConfigInterface interface {
	Create(ctx context.Context, userKubeConfig *v1alpha1.UserKubeConfig, opts v1.CreateOptions) (*v1alpha1.UserKubeConfig, error)
	Update(ctx context.Context, userKubeConfig *v1alpha1.UserKubeConfig, opts v1.UpdateOptions) (*v1alpha1.UserKubeConfig, error)
	UpdateStatus(ctx context.Context, userKubeConfig *v1alpha1.UserKubeConfig, opts v1.UpdateOptions) (*v1alpha1.UserKubeConfig, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.UserKubeConfig, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.UserKubeConfigList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.UserKubeConfig, err error)
	UserKubeConfigExpansion
}

// userKubeConfigs implements UserKubeConfigInterface
type userKubeConfigs struct {
	client rest.Interface
}

// newUserKubeConfigs returns a UserKubeConfigs
func newUserKubeConfigs(c *RbacV1alpha1Client) *userKubeConfigs {
	return &userKubeConfigs{
		client: c.RESTClient(),
	}
}

// Get takes name of the userKubeConfig, and returns the corresponding userKubeConfig object, and an error if there is any.
func (c *userKubeConfigs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.UserKubeConfig, err error) {
	result = &v1alpha1.UserKubeConfig{}
	err = c.client.Get().
		Resource("userkubeconfigs").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of UserKubeConfigs that match those selectors.
func (c *userKubeConfigs) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.UserKubeConfigList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.UserKubeConfigList{}
	err = c.client.Get().
		Resource("userkubeconfigs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested userKubeConfigs.
func (c *userKubeConfigs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("userkubeconfigs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a userKubeConfig and creates it.  Returns the server's representation of the userKubeConfig, and an error, if there is any.
func (c *userKubeConfigs) Create(ctx context.Context, userKubeConfig *v1alpha1.UserKubeConfig, opts v1.CreateOptions) (result *v1alpha1.UserKubeConfig, err error) {
	result = &v1alpha1.UserKubeConfig{}
	err = c.client.Post().
		Resource("userkubeconfigs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(userKubeConfig).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a userKubeConfig and updates it. Returns the server's representation of the userKubeConfig, and an error, if there is any.
func (c *userKubeConfigs) Update(ctx context.Context, userKubeConfig *v1alpha1.UserKubeConfig, opts v1.UpdateOptions) (result *v1alpha1.UserKubeConfig, err error) {
	result = &v1alpha1.UserKubeConfig{}
	err = c.client.Put().
		Resource("userkubeconfigs").
		Name(userKubeConfig.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(userKubeConfig).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *userKubeConfigs) UpdateStatus(ctx context.Context, userKubeConfig *v1alpha1.UserKubeConfig, opts v1.UpdateOptions) (result *v1alpha1.UserKubeConfig, err error) {
	result = &v1alpha1.UserKubeConfig{}
	err = c.client.Put().
		Resource("userkubeconfigs").
		Name(userKubeConfig.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(userKubeConfig).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the userKubeConfig and deletes it. Returns an error if one occurs.
func (c *userKubeConfigs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("userkubeconfigs").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *userKubeConfigs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("userkubeconfigs").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched userKubeConfig.
func (c *userKubeConfigs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.UserKubeConfig, err error) {
	result = &v1alpha1.UserKubeConfig{}
	err = c.client.Patch(pt).
		Resource("userkubeconfigs").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
