/*
Copyright 2022 The kubeall.com Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/kubeall/api/metrics/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeServiceMetricses implements ServiceMetricsInterface
type FakeServiceMetricses struct {
	Fake *FakeMetricsV1alpha1
	ns   string
}

var servicemetricsesResource = schema.GroupVersionResource{Group: "metrics.kubeall.com", Version: "v1alpha1", Resource: "servicemetricses"}

var servicemetricsesKind = schema.GroupVersionKind{Group: "metrics.kubeall.com", Version: "v1alpha1", Kind: "ServiceMetrics"}

// Get takes name of the serviceMetrics, and returns the corresponding serviceMetrics object, and an error if there is any.
func (c *FakeServiceMetricses) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ServiceMetrics, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(servicemetricsesResource, c.ns, name), &v1alpha1.ServiceMetrics{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ServiceMetrics), err
}

// List takes label and field selectors, and returns the list of ServiceMetricses that match those selectors.
func (c *FakeServiceMetricses) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ServiceMetricsList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(servicemetricsesResource, servicemetricsesKind, c.ns, opts), &v1alpha1.ServiceMetricsList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ServiceMetricsList{ListMeta: obj.(*v1alpha1.ServiceMetricsList).ListMeta}
	for _, item := range obj.(*v1alpha1.ServiceMetricsList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested serviceMetricses.
func (c *FakeServiceMetricses) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(servicemetricsesResource, c.ns, opts))

}

// Create takes the representation of a serviceMetrics and creates it.  Returns the server's representation of the serviceMetrics, and an error, if there is any.
func (c *FakeServiceMetricses) Create(ctx context.Context, serviceMetrics *v1alpha1.ServiceMetrics, opts v1.CreateOptions) (result *v1alpha1.ServiceMetrics, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(servicemetricsesResource, c.ns, serviceMetrics), &v1alpha1.ServiceMetrics{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ServiceMetrics), err
}

// Update takes the representation of a serviceMetrics and updates it. Returns the server's representation of the serviceMetrics, and an error, if there is any.
func (c *FakeServiceMetricses) Update(ctx context.Context, serviceMetrics *v1alpha1.ServiceMetrics, opts v1.UpdateOptions) (result *v1alpha1.ServiceMetrics, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(servicemetricsesResource, c.ns, serviceMetrics), &v1alpha1.ServiceMetrics{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ServiceMetrics), err
}

// Delete takes name of the serviceMetrics and deletes it. Returns an error if one occurs.
func (c *FakeServiceMetricses) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(servicemetricsesResource, c.ns, name, opts), &v1alpha1.ServiceMetrics{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeServiceMetricses) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(servicemetricsesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ServiceMetricsList{})
	return err
}

// Patch applies the patch and returns the patched serviceMetrics.
func (c *FakeServiceMetricses) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ServiceMetrics, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(servicemetricsesResource, c.ns, name, pt, data, subresources...), &v1alpha1.ServiceMetrics{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ServiceMetrics), err
}
