/*
Copyright 2022 The kubeall.com Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/kubeall/api/monitor/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeProjectArchitectures implements ProjectArchitectureInterface
type FakeProjectArchitectures struct {
	Fake *FakeMonitorV1alpha1
	ns   string
}

var projectarchitecturesResource = schema.GroupVersionResource{Group: "monitor.kubeall.com", Version: "v1alpha1", Resource: "projectarchitectures"}

var projectarchitecturesKind = schema.GroupVersionKind{Group: "monitor.kubeall.com", Version: "v1alpha1", Kind: "ProjectArchitecture"}

// Get takes name of the projectArchitecture, and returns the corresponding projectArchitecture object, and an error if there is any.
func (c *FakeProjectArchitectures) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ProjectArchitecture, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(projectarchitecturesResource, c.ns, name), &v1alpha1.ProjectArchitecture{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProjectArchitecture), err
}

// List takes label and field selectors, and returns the list of ProjectArchitectures that match those selectors.
func (c *FakeProjectArchitectures) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ProjectArchitectureList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(projectarchitecturesResource, projectarchitecturesKind, c.ns, opts), &v1alpha1.ProjectArchitectureList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ProjectArchitectureList{ListMeta: obj.(*v1alpha1.ProjectArchitectureList).ListMeta}
	for _, item := range obj.(*v1alpha1.ProjectArchitectureList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested projectArchitectures.
func (c *FakeProjectArchitectures) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(projectarchitecturesResource, c.ns, opts))

}

// Create takes the representation of a projectArchitecture and creates it.  Returns the server's representation of the projectArchitecture, and an error, if there is any.
func (c *FakeProjectArchitectures) Create(ctx context.Context, projectArchitecture *v1alpha1.ProjectArchitecture, opts v1.CreateOptions) (result *v1alpha1.ProjectArchitecture, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(projectarchitecturesResource, c.ns, projectArchitecture), &v1alpha1.ProjectArchitecture{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProjectArchitecture), err
}

// Update takes the representation of a projectArchitecture and updates it. Returns the server's representation of the projectArchitecture, and an error, if there is any.
func (c *FakeProjectArchitectures) Update(ctx context.Context, projectArchitecture *v1alpha1.ProjectArchitecture, opts v1.UpdateOptions) (result *v1alpha1.ProjectArchitecture, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(projectarchitecturesResource, c.ns, projectArchitecture), &v1alpha1.ProjectArchitecture{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProjectArchitecture), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeProjectArchitectures) UpdateStatus(ctx context.Context, projectArchitecture *v1alpha1.ProjectArchitecture, opts v1.UpdateOptions) (*v1alpha1.ProjectArchitecture, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(projectarchitecturesResource, "status", c.ns, projectArchitecture), &v1alpha1.ProjectArchitecture{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProjectArchitecture), err
}

// Delete takes name of the projectArchitecture and deletes it. Returns an error if one occurs.
func (c *FakeProjectArchitectures) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(projectarchitecturesResource, c.ns, name, opts), &v1alpha1.ProjectArchitecture{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeProjectArchitectures) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(projectarchitecturesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ProjectArchitectureList{})
	return err
}

// Patch applies the patch and returns the patched projectArchitecture.
func (c *FakeProjectArchitectures) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ProjectArchitecture, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(projectarchitecturesResource, c.ns, name, pt, data, subresources...), &v1alpha1.ProjectArchitecture{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProjectArchitecture), err
}
