/*
Copyright 2022 The kubeall.com Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	monitoringv1alpha1 "github.com/kubeall/api/monitoring/v1alpha1"
	versioned "github.com/kubeall/client-go/monitoring/clientset/versioned"
	internalinterfaces "github.com/kubeall/client-go/monitoring/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/kubeall/client-go/monitoring/listers/monitoring/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ProjectArchitectureInformer provides access to a shared informer and lister for
// ProjectArchitectures.
type ProjectArchitectureInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.ProjectArchitectureLister
}

type projectArchitectureInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewProjectArchitectureInformer constructs a new informer for ProjectArchitecture type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewProjectArchitectureInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredProjectArchitectureInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredProjectArchitectureInformer constructs a new informer for ProjectArchitecture type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredProjectArchitectureInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.MonitoringV1alpha1().ProjectArchitectures(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.MonitoringV1alpha1().ProjectArchitectures(namespace).Watch(context.TODO(), options)
			},
		},
		&monitoringv1alpha1.ProjectArchitecture{},
		resyncPeriod,
		indexers,
	)
}

func (f *projectArchitectureInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredProjectArchitectureInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *projectArchitectureInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&monitoringv1alpha1.ProjectArchitecture{}, f.defaultInformer)
}

func (f *projectArchitectureInformer) Lister() v1alpha1.ProjectArchitectureLister {
	return v1alpha1.NewProjectArchitectureLister(f.Informer().GetIndexer())
}
