/*
Copyright 2022 The kubeall.com Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/kubeall/api/metrics/v1alpha1"
	scheme "github.com/kubeall/client-go/metrics/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ServiceMetricsesGetter has a method to return a ServiceMetricsInterface.
// A group's client should implement this interface.
type ServiceMetricsesGetter interface {
	ServiceMetricses(namespace string) ServiceMetricsInterface
}

// ServiceMetricsInterface has methods to work with ServiceMetrics resources.
type ServiceMetricsInterface interface {
	Create(ctx context.Context, serviceMetrics *v1alpha1.ServiceMetrics, opts v1.CreateOptions) (*v1alpha1.ServiceMetrics, error)
	Update(ctx context.Context, serviceMetrics *v1alpha1.ServiceMetrics, opts v1.UpdateOptions) (*v1alpha1.ServiceMetrics, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.ServiceMetrics, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.ServiceMetricsList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ServiceMetrics, err error)
	ServiceMetricsExpansion
}

// serviceMetricses implements ServiceMetricsInterface
type serviceMetricses struct {
	client rest.Interface
	ns     string
}

// newServiceMetricses returns a ServiceMetricses
func newServiceMetricses(c *MetricsV1alpha1Client, namespace string) *serviceMetricses {
	return &serviceMetricses{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the serviceMetrics, and returns the corresponding serviceMetrics object, and an error if there is any.
func (c *serviceMetricses) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ServiceMetrics, err error) {
	result = &v1alpha1.ServiceMetrics{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("servicemetricses").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ServiceMetricses that match those selectors.
func (c *serviceMetricses) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ServiceMetricsList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.ServiceMetricsList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("servicemetricses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested serviceMetricses.
func (c *serviceMetricses) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("servicemetricses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a serviceMetrics and creates it.  Returns the server's representation of the serviceMetrics, and an error, if there is any.
func (c *serviceMetricses) Create(ctx context.Context, serviceMetrics *v1alpha1.ServiceMetrics, opts v1.CreateOptions) (result *v1alpha1.ServiceMetrics, err error) {
	result = &v1alpha1.ServiceMetrics{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("servicemetricses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(serviceMetrics).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a serviceMetrics and updates it. Returns the server's representation of the serviceMetrics, and an error, if there is any.
func (c *serviceMetricses) Update(ctx context.Context, serviceMetrics *v1alpha1.ServiceMetrics, opts v1.UpdateOptions) (result *v1alpha1.ServiceMetrics, err error) {
	result = &v1alpha1.ServiceMetrics{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("servicemetricses").
		Name(serviceMetrics.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(serviceMetrics).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the serviceMetrics and deletes it. Returns an error if one occurs.
func (c *serviceMetricses) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("servicemetricses").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *serviceMetricses) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("servicemetricses").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched serviceMetrics.
func (c *serviceMetricses) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ServiceMetrics, err error) {
	result = &v1alpha1.ServiceMetrics{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("servicemetricses").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
